[pytest]

addopts =
    -v
    -s
    --tb=short
    --alluredir=reports/allure-results
testpaths =
    tests

python_files =
    test_*.py

python_classes =
    Test*

python_functions =
    test_*

log_cli = true

log_cli_level = INFO

log_cli_format =
    %(asctime)s | %(levelname)s | %(message)s

log_cli_date_format =
    %Y-%m-%d %H:%M:%S


markers =
    smoke: smoke execution
    regression: regression suite
    api: api tests
    schema: schema validation
    retry: retry execution
    parallel: parallel execution